controller_frequency: 5

TrajectoryPlannerROS:
  max_vel_x: 0.4 #1.0 #0.5
  min_vel_x: -0.1 #0.01
  max_vel_theta: 1.57 #1.5


  min_in_place_vel_theta: 0.314

  acc_lim_theta: 3.14
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  sim_time: 2.0 #2.5
  sim_granularity: 0.0314

  vx_samples:  7.0
  vtheta_samples: 15.0

  pdist_scale: 0.6 #0.8 #0.6
  gdist_scale: 0.85 #1.6 #0.8
  occdist_scale: 0.5

#  holonomic_robot: false

#  meter_scoring: true
